Merge hotfix
skalenetwork/IMA pull request #1287
Opened 2022-09-22 15:17 UTC by DimaStebaev

2022-09-22 15:19 UTC, payvint approved these changes, later dismissed

2022-09-22 16:37 UTC, sergiy-skalelabs approved these changes

2022-09-23 11:00 UTC, sergiy-skalelabs requested changes, later dismissed
roll back all JS code to original develop version

2022-09-27 09:33 UTC, payvint approved these changes

2022-09-27 10:54 UTC, sergiy-skalelabs approved these changes

2022-09-27 11:04 UTC, yavrsky approved these changes

2022-09-27 11:09 UTC, gannakulikova approved these changes

2022-09-27 11:10 UTC, merged