Prepare 2.2.0 release candidate
skalenetwork/IMA pull request #1727
Opened 2024-11-19 18:35 UTC by yavrsky

2024-11-19 22:19 UTC, DmytroNazarenko requested changes

2024-11-19 22:19 UTC, DmytroNazarenko commented on .github/workflows/publish.yml
>      tags:
You need to add `release-candidate` branch to make publish.yml work

2024-11-19 22:20 UTC, DmytroNazarenko approved these changes

2024-11-20 13:17 UTC, DimaStebaev approved these changes

2024-11-20 13:18 UTC, merged