Docs v1.0.x add erc721 ima js
skalenetwork/IMA pull request #824
Opened 2021-09-16 17:01 UTC by dmitry-tk

2021-09-16 17:17 UTC, sergiy-skalelabs approved these changes

2021-09-16 19:16 UTC, cstrangedk requested changes
development-with-ima-sdk.adoc is a repeat of https://github.com/skalenetwork/docs.skale.network/blob/master/components/develop/modules/ROOT/pages/ima-sdk.adoc.  Please add additions/changes to https://github.com/skalenetwork/docs.skale.network/blob/master/components/develop/modules/ROOT/pages/ima-sdk.adoc instead

2021-09-17 12:44 UTC, dmitry-tk commented
@cstrangedk 
Addressed requested changes

2021-09-17 14:16 UTC, cstrangedk approved these changes

2021-09-17 14:16 UTC, merged