Enhancement/skale 4626 upgrade script schain
skalenetwork/IMA pull request #842
Opened 2021-09-30 14:57 UTC by payvint

2021-10-01 12:55 UTC, yavrsky submitted a review, later dismissed

2021-10-05 11:25 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-05 12:10 UTC, yavrsky approved these changes, later dismissed

2021-10-22 08:29 UTC, DimaStebaev requested changes

2021-10-22 08:29 UTC, DimaStebaev commented on .github/workflows/publish.yml
> +        assets_path: proxy/data/manifest.json
The filename should be more descriptive and contains component and version.
Something similar to "ima-$VERSION-manifest.json"

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/changeManifest.ts
> +export async function change() {
Is this file used somewhere?
How to get output?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/deploySchain.ts
> +export const contractsToDeploy = [
What is difference between `contractsToDeploy` and `contracts`?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/deploySchain.ts
> +        return "message_proxy_chain";
Why do not store the contract with original name?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +export const predeployedAddresses: any = {
This one duplicates values in `ima-predeployed`.

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +export const predeployedAddresses: any = {
I think it's a bad idea to allow generation only for default addresses. Why not parameterize it?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +export async function getImplKey(contractName: string) {
What is `ImplKey`?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +async function getImplementationDeployment(contractName: string, addresses: any): Promise<ImplDeployment> {
`addresses` can be only object or dictionary. Not any.

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +function defaultManifest(): ManifestData {
Default or empty?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +export async function generateManifest(addresses: any) {
`addresses` can't be any.

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +    await fs.writeFile("data/manifest.json", JSON.stringify(newManifest, null, 4));
"manifest.json" is a bad filename. There is not component name nor version.

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +function findProxyContract(data: any, address: string) {
It is really used?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +export async function importAddresses(manifest: any, abi: any) {
It is really used?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +export async function manifestSetup(pathToManifest: any) {
Is `pathToManifest` not string?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +        fs.access(`.openzeppelin/unknown-${chainId}.json`, constants.R_OK | constants.W_OK);
Is it not already checked?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +    try {
Will this block be ever executed successfully?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +        fs.access( pathToManifest, constants.R_OK | constants.W_OK );
Is it not already checked?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +            await fs.rename( pathToManifest, `.openzeppelin/unknown-${chainId}.json` );
What do you think about copying instead of renaming?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/tools/gnosis-safe.ts
> +        if (!e.toString().startsWith("Error: Can't get safe-transaction url") && !e.toString().startsWith("Error: Request failed with status code 404")) {
You broke the condition. It is never true now.

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/migrations/upgrade.ts
> +export async function upgrade(
You take on engineering debt.
See SKALE-4680

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/scripts/test_upgrade.sh
> +npx ganache-cli --gasLimit 30000000 --quiet --allowUnlimitedContractSize &
Do we need so big gas limit?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/scripts/test_upgrade.sh
> +cp "$GITHUB_WORKSPACE/proxy/migrations/deploySchain.ts" ./migrations/deploySchain.ts
Is it safe to deploy old IMA with new script?

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/scripts/test_upgrade.sh
> +ABI="data/$ABI_FILENAME_SCHAIN" MANIFEST=".openzeppelin/unknown-1337.json" npx hardhat run migrations/changeManifest.ts --network localhost || exit $?
In real world we may do not have existing manifest.
I argue that it's better to use generateManifest functionality.

2021-10-22 08:29 UTC, DimaStebaev commented on proxy/tslint.json
> +        "no-bitwise": false
What is a rationale to disable this warning?
Don't you have typo somewhere?

2021-10-22 08:40 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-22 08:43 UTC, payvint commented on .github/workflows/publish.yml
> +        assets_path: proxy/data/manifest.json
Yes, good point I will suggest to have "ima-schain-${VERSION}-manifest.json

2021-10-22 08:46 UTC, payvint commented on proxy/migrations/deploySchain.ts
> +        return "message_proxy_chain";
It is legacy, to change name in abi - need to change other components, it is good to have a separate task for it

2021-10-22 08:47 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +export const predeployedAddresses: any = {
It is parametrized, all addresses passed as an input variable in generateManifest function

2021-10-22 08:49 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +export const predeployedAddresses: any = {
Yeah predeployed addresses already are in ima-predeployed, decided to copy it in this file. I think it is good idea, just to copy it instead of importing from Python file

2021-10-22 08:55 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +export async function getImplKey(contractName: string) {
ImplKey - implementation key
Technically it is a hash of byte code without metadata - in open zeppelin name is "version". In manifest file it is an "impls" object which contains set of implementation params(storage layout and address) and its lays as dictionary (key -> value) and key is a hash of byte code without metadata - decided to name it implKey:)

2021-10-22 08:55 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +async function getImplementationDeployment(contractName: string, addresses: any): Promise<ImplDeployment> {
Good point, will fix it

2021-10-22 08:56 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +function defaultManifest(): ManifestData {
The same name from the core of open zeppelin core lib

2021-10-22 08:56 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +export async function generateManifest(addresses: any) {
Good point, will fix it

2021-10-22 08:57 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +    await fs.writeFile("data/manifest.json", JSON.stringify(newManifest, null, 4));
Will change a name as described above

2021-10-22 10:19 UTC, payvint commented on proxy/migrations/changeManifest.ts
> +export async function change() {
Yes it is used in test_upgrade - after deployment of schain part of IMA contracts new contract addresses would be generating - so we testing function "generateManifest" with new addresses in test_upgrade

2021-10-22 10:21 UTC, payvint commented on proxy/scripts/test_upgrade.sh
> +cp "$GITHUB_WORKSPACE/proxy/migrations/deploySchain.ts" ./migrations/deploySchain.ts
Yes it is safe, we did not add keySstorage to the abi in the past and added it in a new script

2021-10-22 10:21 UTC, payvint commented on proxy/scripts/test_upgrade.sh
> +npx ganache-cli --gasLimit 30000000 --quiet --allowUnlimitedContractSize &
Just copy current mainnet gas limit

2021-10-22 10:22 UTC, payvint commented on proxy/scripts/test_upgrade.sh
> +ABI="data/$ABI_FILENAME_SCHAIN" MANIFEST=".openzeppelin/unknown-1337.json" npx hardhat run migrations/changeManifest.ts --network localhost || exit $?
It is just for test - we use generateManifest inside - but we need new addresses

2021-10-22 10:25 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +function findProxyContract(data: any, address: string) {
Yeah in importAddresses

2021-10-22 10:25 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +export async function importAddresses(manifest: any, abi: any) {
Yeah in changeManifest

2021-10-22 10:28 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +export async function manifestSetup(pathToManifest: any) {
Will fix it

2021-10-22 10:34 UTC, payvint commented on proxy/migrations/tools/gnosis-safe.ts
> +        if (!e.toString().startsWith("Error: Can't get safe-transaction url") && !e.toString().startsWith("Error: Request failed with status code 404")) {
Yes will fix it

2021-10-22 10:40 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +    try {
It is already executed in GA

2021-10-22 10:42 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +        fs.access(`.openzeppelin/unknown-${chainId}.json`, constants.R_OK | constants.W_OK);
Nope

2021-10-22 10:42 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +        fs.access( pathToManifest, constants.R_OK | constants.W_OK );
Nope

2021-10-22 10:43 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +            await fs.rename( pathToManifest, `.openzeppelin/unknown-${chainId}.json` );
Yeah good idea

2021-10-22 10:44 UTC, payvint commented on proxy/migrations/upgrade.ts
> +export async function upgrade(
Yeah we will implement separate package it in the task 4680

2021-10-22 10:45 UTC, payvint commented on proxy/tslint.json
> +        "no-bitwise": false
It is used in fs.access in manifestSetup function in generateManifest file

2021-10-22 10:47 UTC, payvint commented on proxy/migrations/generateManifest.ts
> +function defaultManifest(): ManifestData {
Will fix it

2021-10-22 10:49 UTC, payvint commented on proxy/migrations/deploySchain.ts
> +export const contractsToDeploy = [
Will remove contracts - it is never used

2021-10-22 12:10 UTC, yavrsky submitted a review, later dismissed

2021-10-22 12:23 UTC, DimaStebaev commented on proxy/migrations/generateManifest.ts
> +export async function getImplKey(contractName: string) {
It looks like the function returns version and it is used as a key later.
So effectively function must be called `getVersion` and the result then be used as a key in set.
const key = getVersion('Contract`). It will reflect what is going on.
Or at list there should be a comment that describes it.

2021-10-22 12:23 UTC, DimaStebaev commented on proxy/scripts/test_upgrade.sh
> +npx ganache-cli --gasLimit 30000000 --quiet --allowUnlimitedContractSize &
After London fork it can be lower. Why do not left more strict limit in test to be sure that it will work on mainnet?

2021-10-22 12:23 UTC, DimaStebaev commented on proxy/scripts/test_upgrade.sh
> +cp "$GITHUB_WORKSPACE/proxy/migrations/deploySchain.ts" ./migrations/deploySchain.ts
But new script may be modified if we add new contract for example. And this contract will be absent in stable version.

2021-10-22 12:23 UTC, DimaStebaev commented on proxy/scripts/test_upgrade.sh
> +ABI="data/$ABI_FILENAME_SCHAIN" MANIFEST=".openzeppelin/unknown-1337.json" npx hardhat run migrations/changeManifest.ts --network localhost || exit $?
On mainnet upgrade will be different. This test verifies theoretical situation.

2021-10-22 12:23 UTC, DimaStebaev commented on proxy/tslint.json
> +        "no-bitwise": false
Let's just use fs.access with default mode.

2021-10-22 13:22 UTC, yavrsky submitted a review, later dismissed

2021-10-22 13:26 UTC, yavrsky submitted a review, later dismissed

2021-10-22 13:29 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-22 14:27 UTC, DimaStebaev commented on proxy/migrations/tools/gnosis-safe.ts
> +        if (!e.toString().startsWith("Error: Can't get safe-transaction url") && !e.toString().startsWith("Error: Request failed with status code 404")) {
I'm wrong. It may be true.
But in most cases when we receive 404 we must stop upgrade.

2021-10-25 08:24 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-25 12:23 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-25 12:42 UTC, yavrsky submitted a review, later dismissed

2021-10-25 13:48 UTC, DimaStebaev submitted a review, later dismissed

2021-10-25 13:48 UTC, DimaStebaev commented on proxy/migrations/tools/gnosis-safe.ts
> +export async function createMultiSendTransaction(ethers: any, safeAddress: string, privateKey: string, transactions: string[], isSafeMock: boolean) {
What about adding default value for `isSafeMock` is false?

2021-10-25 15:59 UTC, sergiy-skalelabs approved these changes

2021-10-25 15:59 UTC, DimaStebaev approved these changes

2021-10-25 16:06 UTC, yavrsky approved these changes

2021-10-25 16:10 UTC, merged