SKALE-4689 add is contract check and test
skalenetwork/IMA pull request #873
Opened 2021-10-22 13:51 UTC by payvint

2021-10-22 13:52 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-22 14:21 UTC, yavrsky submitted a review, later dismissed

2021-10-25 09:26 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-25 12:23 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-10-25 12:32 UTC, yavrsky submitted a review, later dismissed

2021-10-25 14:26 UTC, DimaStebaev requested changes

2021-10-25 14:26 UTC, DimaStebaev commented on proxy/migrations/upgradeMainnet.ts
> +                console.log(chalk.red("Check your abi!!!"));
Exit here.

2021-10-25 14:26 UTC, DimaStebaev commented on proxy/test/extensions/ERC721MintingFromSchainToMainnet.ts
> +            expect(resPost.events[0]?.topics[0]).to.equal(stringValue(web3.utils.soliditySha3("PostMessageError(uint256,bytes)")));
Do not hardcode event indexes.
Use `waffle` instead.
https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#emitting-events

2021-10-25 14:26 UTC, DimaStebaev commented on proxy/test/extensions/ERC721MintingFromSchainToMainnet.ts
> +        const BlsSignature: [BigNumber, BigNumber] = [
Use something obviously incorrect. For example (0, 0, 1, 0).

2021-10-25 14:26 UTC, DimaStebaev commented on proxy/migrations/upgradeMainnet.ts
> +                safeTransactions.push(encodeTransaction(
Grant role only if it is needed.

2021-10-25 16:29 UTC, payvint commented on proxy/test/extensions/ERC721MintingFromSchainToMainnet.ts
> +        const BlsSignature: [BigNumber, BigNumber] = [
Nope

2021-10-25 16:58 UTC, yavrsky approved these changes

2021-10-25 16:59 UTC, DimaStebaev approved these changes

2021-10-25 17:11 UTC, merged